### PR TITLE
Fix TcpOutput recovery from full queue when using 'block' or

### LINKED ISSUE #1484: TcpOutput queue_full_action = "block" block forever
Hi,

I'm using heka to ship log to another heka (receiver) with TcpOutput,
and i want to use queue_max_buffer_size so my server doesn't blow up if receiver is down,
and queue_full_action = "block" so that it start again when receiver is up again or ...

Maybe i'm not understanding "block" option right?

here is my shipper config (access.log is 1000000 lines long/250Mo)
i've put a small queue_max_buffer_size to be sure to hit it
```
[nginxaccess]
type = "LogstreamerInput"
log_directory = "/tmp/"
file_match = 'access\.log\.?(?P<Seq>\d*)'
priority = ["^Seq"]
oldest_duration = "2h"
decoder = "AccessDecoder"

[AccessDecoder]
type = "SandboxDecoder"
filename = "lua_decoders/nginx_access.lua"

[AccessDecoder.config]
type = "access.log"
log_format = '$time_iso8601|$remote_addr|$request_length|$bytes_sent|$request_time|$upstream_response_time|$gzip_ratio|$status|$remote_user|$request|$http_referer|$http_user_agent|$http_x_forwarded_for'

[TcpOutput]
address = "<remote>:5565"
message_matcher = "TRUE"
ticker_interval = 10
queue_max_buffer_size = 1485760
queue_full_action = "block"
```

here is my receiver
```
[TcpInput]
address = ":5565"
keep_alive = true
keep_alive_period = 120

[RstEncoder]

[LogOutput]
message_matcher = "TRUE"
encoder = "RstEncoder"
```

### PR DESCRIPTION
**Pull request by rafrombrc**
'drop' as the queue_full_action, fixes #1484.

### CODE REVIEW

File: pipeline/buffered_output.go [hunk 1]
```diff
@@ -98,9 +101,21 @@ func (b *BufferedOutput) QueueBytes(msgBytes []byte) (err error) {
 
 	if b.maxQueueSize > 0 && (b.queueSize+uint64(len(msgBytes))) > b.maxQueueSize {
 		err = QueueIsFull
```
Comment (trink) [inline pipeline/buffered_output.go]: Update the queue full unit tests to verify the roll guard invocation and reset

**Comment by rafrombrc** [comment]
Added.
