### PR TITLE
PluginMaker overhaul to remove cached config state.

### LINKED ISSUE #1532: Panic when creating multiple copies of the same decoder from different go routines.
config.go line 816 is modifying a structure it only has a read lock on creating a race condition.

```
2015/05/14 14:18:29 Input started: TelemetryInput
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x30 pc=0x49033c]

goroutine 72 [running]:
github.com/mozilla-services/heka/pipeline.(*ProtobufDecoder).Init(0x0, 0x9a4b60, 0xc2080926f0, 0x0, 0x7f5b3bde5960)
	/work/git/data-pipeline/build/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/protobuf.go:46 +0xc
github.com/mozilla-services/heka/pipeline.(*pluginMaker).Make(0xc208064480, 0x0, 0x0, 0x0, 0x0)
	/work/git/data-pipeline/build/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/config.go:819 +0x127
github.com/mozilla-services/heka/pipeline.(*pluginMaker).MakeRunner(0xc208064480, 0xc2080920f0, 0x28, 0x0, 0x0, 0x0, 0x0)
	/work/git/data-pipeline/build/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/config.go:923 +0x205
github.com/mozilla-services/heka/pipeline.(*PipelineConfig).DecoderRunner(0xc2080b4380, 0xc208070bc0, 0xf, 0xc2080920f0, 0x28, 0x0, 0x0, 0x1)
	/work/git/data-pipeline/build/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/config.go:303 +0x13b
github.com/mozilla-services/heka/pipeline.(*iRunner).getDeliverFunc(0xc20810a240, 0xc208116030, 0x9, 0x10, 0x0, 0x0, 0x0, 0x0)
	/work/git/data-pipeline/build/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/plugin_runners.go:431 +0x57a
github.com/mozilla-services/heka/pipeline.(*iRunner).NewDeliverer(0xc20810a240, 0xc208116030, 0x9, 0x0, 0x0)
	/work/git/data-pipeline/build/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/plugin_runners.go:490 +0x5a
github.com/mozilla-services/data-pipeline/s3splitfile.(*S3SplitFileInput).fetcher(0xc208062500, 0x7f5b3bdfd168, 0xc20810a240, 0xc20801e560, 0x5)
	/work/git/data-pipeline/build/heka/build/heka/src/github.com/mozilla-services/data-pipeline/s3splitfile/s3splitfile_input.go:178 +0x1b7
created by github.com/mozilla-services/data-pipeline/s3splitfile.(*S3SplitFileInput).Run
	/work/git/data-pipeline/build/heka/build/heka/src/github.com/mozilla-services/data-pipeline/s3splitfile/s3splitfile_input.go:137 +0x1bb
```

### PR DESCRIPTION
**Pull request by rafrombrc**
Fixes #1532.

### CODE REVIEW

File: sandbox/plugins/sandbox_manager_filter.go [hunk 1]
```diff
@@ -244,6 +247,7 @@ func (this *SandboxManagerFilter) restoreSandboxes(fr pipeline.FilterRunner,
 	glob := fmt.Sprintf("%s-*.toml", getNormalizedName(fr.Name()))
 	if matches, err := filepath.Glob(filepath.Join(dir, glob)); err == nil {
 		for _, fn := range matches {
+			fmt.Println("match fn: ", fn)
```
Comment (trink) [inline sandbox/plugins/sandbox_manager_filter.go]: Remove debug print statement

File: sandbox/plugins/sandbox_filters_test.go [hunk 2]
```diff
@@ -2,6 +2,10 @@ package plugins
```
Comment (trink) [inline sandbox/plugins/sandbox_filters_test.go]: Not sure why his is part of the diff since the file didn't need to be touched but ok.

**Comment by rafrombrc** [comment]
Fixed.
